// BNY 50-storefronts roster (PLAN-50-STORES.md) — the consent-gated program
// for onboarding real Brooklyn Navy Yard tenants into the GrahmOS Virtual Mall.
// Every profile starts "unclaimed": unclaimed profiles are DISPLAY-ONLY and
// NON-TRANSACTING (no checkout, no pricing, no implied affiliation) until the
// business claims and verifies its storefront. Data is sourced verbatim from
// research/bny-top50.json (brooklynnavyyard.org tenant directory + each
// business's public site).

export type ClaimStatus = "unclaimed" | "pending_verification" | "claimed";

export interface BnyStorefront {
  id: string; // `bny_${rank padded to 2}` e.g. "bny_01"
  rank: number;
  slug: string;
  name: string;
  aisle: string; // one of the 8 aisle slugs in mallData.ts AISLES
  website: string;
  ecommerceHint: "store" | "unknown" | "none";
  signals: string;
  description: string;
  cohort: 1 | 2 | 3;
  claimStatus: ClaimStatus; // all start "unclaimed"
  attribution: string;
  icon: string;
}

function attribution(name: string): string {
  return `Source: brooklynnavyyard.org tenant directory · ${name}'s public site`;
}

export const BNY_ROSTER: BnyStorefront[] = [
  {
    id: "bny_01",
    rank: 1,
    slug: "russ-daughters",
    name: "Russ & Daughters",
    aisle: "food-beverage",
    website: "https://www.russanddaughters.com/",
    ecommerceHint: "store",
    signals: "Open since 1914; fourth-generation family business; anchors the Building 77 food hall with retail counter and nationwide shipping hub",
    description: "Russ & Daughters is a beloved New York institution, serving up smoked fish, caviar, bagels, and babka, with a Building 77 retail outpost, production bakery and kitchens, and nationwide shipping hub.",
    cohort: 1,
    claimStatus: "unclaimed",
    attribution: attribution("Russ & Daughters"),
    icon: "🥯",
  },
  {
    id: "bny_02",
    rank: 2,
    slug: "atoms",
    name: "Atoms",
    aisle: "apparel-merch",
    website: "https://atoms.com",
    ecommerceHint: "store",
    signals: "Vogue said Atoms might be the most thoughtfully designed sneakers ever; first shoes in 1/4 sizes",
    description: "Atoms is a newly launched brand that makes everyday shoes focused on magical comfort and simple design, the first shoes to come in 1/4 sizes.",
    cohort: 1,
    claimStatus: "unclaimed",
    attribution: attribution("Atoms"),
    icon: "👟",
  },
  {
    id: "bny_03",
    rank: 3,
    slug: "catbird",
    name: "Catbird",
    aisle: "apparel-merch",
    website: "https://www.catbirdnyc.com/",
    ecommerceHint: "store",
    signals: "employs over 30 community residents with plans to hire more; two Williamsburg retail locations; expanding to 1,300 sq ft in Building 77 for design, manufacturing, and distribution",
    description: "Brooklyn-based and woman-owned, Catbird is a jewelry design and manufacturing company specializing in boutique style jewelry made locally with ethically sourced materials and conflict-free stones.",
    cohort: 1,
    claimStatus: "unclaimed",
    attribution: attribution("Catbird"),
    icon: "💍",
  },
  {
    id: "bny_04",
    rank: 4,
    slug: "stick-with-me-sweets",
    name: "Stick With Me Sweets",
    aisle: "food-beverage",
    website: "https://swmsweets.com/",
    ecommerceHint: "store",
    signals: "Led by a Top Ten Chocolatier of America; named one of the best chocolate shops in America; featured in Oprah's Favorite Things, Vogue, Michelin Guide, Bon Appetit, and The New York Times",
    description: "Stick With Me is New York's finest confectionery, specializing in luxurious hand-crafted bonbons, caramels, chocolate truffles, and candy bars.",
    cohort: 1,
    claimStatus: "unclaimed",
    attribution: attribution("Stick With Me Sweets"),
    icon: "🍫",
  },
  {
    id: "bny_05",
    rank: 5,
    slug: "kings-county-distillery",
    name: "Kings County Distillery",
    aisle: "food-beverage",
    website: "http://www.kingscountydistillery.com/",
    ecommerceHint: "unknown",
    signals: "NYC's oldest operating whiskey distillery; awards from ADI, ACSA, and San Francisco World Spirits Competition; praised by NYT, GQ, The New Yorker",
    description: "Kings County Distillery is New York City's oldest operating whiskey distillery, making handmade moonshine, bourbon, and other whiskeys since 2010.",
    cohort: 1,
    claimStatus: "unclaimed",
    attribution: attribution("Kings County Distillery"),
    icon: "🥃",
  },
  {
    id: "bny_06",
    rank: 6,
    slug: "aurate",
    name: "Aurate",
    aisle: "apparel-merch",
    website: "https://auratenewyork.com/",
    ecommerceHint: "store",
    signals: "DTC fine jewelry brand with sustainability and transparent-pricing positioning",
    description: "Aurate is a fine jewelry brand focused on durable materials, transparent pricing, sustainable practices, and tangible giving.",
    cohort: 1,
    claimStatus: "unclaimed",
    attribution: attribution("Aurate"),
    icon: "💎",
  },
  {
    id: "bny_07",
    rank: 7,
    slug: "ecco-shoes",
    name: "ECCO Shoes",
    aisle: "apparel-merch",
    website: "https://us.ecco.com/",
    ecommerceHint: "store",
    signals: "global premium footwear and leather goods brand",
    description: "ECCO's vision is to be the leading premium brand for shoes and leather goods, with work based on quality craftsmanship.",
    cohort: 1,
    claimStatus: "unclaimed",
    attribution: attribution("ECCO Shoes"),
    icon: "👞",
  },
  {
    id: "bny_08",
    rank: 8,
    slug: "noho-health-solutions",
    name: "Care/of",
    aisle: "food-beverage",
    website: "https://www.takecareof.com/",
    ecommerceHint: "store",
    signals: "National DTC supplement brand operating manufacturing at the Yard",
    description: "Science-backed supplements & tools to help you feel a difference from your health routine.",
    cohort: 1,
    claimStatus: "unclaimed",
    attribution: attribution("Care/of"),
    icon: "💊",
  },
  {
    id: "bny_09",
    rank: 9,
    slug: "brooklyn-roasting-company",
    name: "Brooklyn Roasting Company",
    aisle: "food-beverage",
    website: "http://www.brooklynroasting.com/",
    ecommerceHint: "store",
    signals: "Fair Trade and Rainforest Alliance certified coffees; beans locally roasted daily; state-of-the-art production facilities",
    description: "The Brooklyn Roasting Company sources, roasts and brews superb and sustainable coffees from the world's most renowned growing regions and farms.",
    cohort: 1,
    claimStatus: "unclaimed",
    attribution: attribution("Brooklyn Roasting Company"),
    icon: "☕",
  },
  {
    id: "bny_10",
    rank: 10,
    slug: "te-company",
    name: "Té Company",
    aisle: "food-beverage",
    website: "https://tecompanytea.com/",
    ecommerceHint: "store",
    signals: "Featured in the New York Times, New Yorker, New York Magazine, Saveur, and Remodelista; tearoom in the West Village since 2015",
    description: "Established in 2012, Té Company is a NYC based tea company specializing in oolong teas sourced directly from tea farmers of Taiwan, retailing loose-leaf teas, tea snacks, teaware and gifts in their West Village tearoom and online.",
    cohort: 1,
    claimStatus: "unclaimed",
    attribution: attribution("Té Company"),
    icon: "🍵",
  },
  {
    id: "bny_11",
    rank: 11,
    slug: "lafayette-148-new-york",
    name: "Lafayette 148 New York",
    aisle: "apparel-merch",
    website: "https://www.lafayette148ny.com/",
    ecommerceHint: "unknown",
    signals: "One of the few genuinely vertically integrated fashion houses in the world; design HQ at BNY with own atelier in Shantou",
    description: "Lafayette 148 New York is a modern American luxury fashion House led by women, for women, founded in 1996.",
    cohort: 2,
    claimStatus: "unclaimed",
    attribution: attribution("Lafayette 148 New York"),
    icon: "👗",
  },
  {
    id: "bny_12",
    rank: 12,
    slug: "poolside",
    name: "Poolside",
    aisle: "apparel-merch",
    website: "https://www.wearepoolside.com",
    ecommerceHint: "store",
    signals: "Retailing globally at over 100 stores as well as online via their e-commerce shop",
    description: "Poolside is a vacation fashion brand working with female artisans around the world to deliver unique and custom accessories, clothing, beauty, and more.",
    cohort: 2,
    claimStatus: "unclaimed",
    attribution: attribution("Poolside"),
    icon: "👒",
  },
  {
    id: "bny_13",
    rank: 13,
    slug: "crye-precision",
    name: "Crye Precision",
    aisle: "apparel-merch",
    website: "http://www.cryeprecision.com/",
    ecommerceHint: "unknown",
    signals: "employs over 200 people; expanding into 85,000 sq ft at the Green Manufacturing Center; made in America with American materials; outfits nearly every U.S. service member",
    description: "Crye Precision designs and manufactures combat-proven protective equipment for U.S. Special Operations Forces.",
    cohort: 2,
    claimStatus: "unclaimed",
    attribution: attribution("Crye Precision"),
    icon: "🪖",
  },
  {
    id: "bny_14",
    rank: 14,
    slug: "simulate",
    name: "SIMULATE",
    aisle: "food-beverage",
    website: "https://simulate.com/",
    ecommerceHint: "store",
    signals: "",
    description: "Nutrition technology startup SIMULATE makes chicken-like nuggets from plants.",
    cohort: 2,
    claimStatus: "unclaimed",
    attribution: attribution("SIMULATE"),
    icon: "🌱",
  },
  {
    id: "bny_15",
    rank: 15,
    slug: "b-stuyvesant-champagne",
    name: "B. Stuyvesant Champagne",
    aisle: "food-beverage",
    website: "https://www.stuyvesantchampagne.com",
    ecommerceHint: "store",
    signals: "Black, woman-owned champagne brand sourced from France",
    description: "B. Stuyvesant Champagne is a transformative blend of tradition and innovation, sourced from France, celebrating inclusivity, diversity, and empowerment.",
    cohort: 2,
    claimStatus: "unclaimed",
    attribution: attribution("B. Stuyvesant Champagne"),
    icon: "🍾",
  },
  {
    id: "bny_16",
    rank: 16,
    slug: "kitsby",
    name: "Kitsby",
    aisle: "food-beverage",
    website: "https://www.kitsby.com/",
    ecommerceHint: "store",
    signals: "Sells kits and mixes online at kitsby.com plus a retail dessert bar",
    description: "Kitsby is a baking kit company and dessert restaurant, selling kits and mixes online and running an Asian-inspired dessert bar in Williamsburg.",
    cohort: 2,
    claimStatus: "unclaimed",
    attribution: attribution("Kitsby"),
    icon: "🧁",
  },
  {
    id: "bny_17",
    rank: 17,
    slug: "sulsung-foods",
    name: "Kim'C Market",
    aisle: "food-beverage",
    website: "https://kimcmarket.com/",
    ecommerceHint: "store",
    signals: "Operates an online grocery storefront",
    description: "aka Sulsung Foods; Kim'C Market is an online Korean grocery store, offering a wide range of Korean food products at best prices with high quality.",
    cohort: 2,
    claimStatus: "unclaimed",
    attribution: attribution("Kim'C Market"),
    icon: "🍜",
  },
  {
    id: "bny_18",
    rank: 18,
    slug: "jalapa-jar",
    name: "Jalapa Jar",
    aisle: "food-beverage",
    website: "https://jalapajar.com/",
    ecommerceHint: "unknown",
    signals: "Stocked at Whole Foods and other tri-state retailers; also caters events",
    description: "Jalapa Jar is a manufacturer of fresh, all-natural salsas found at Whole Foods and other retailers around the tri-state area, with a taco shop in Building 77.",
    cohort: 2,
    claimStatus: "unclaimed",
    attribution: attribution("Jalapa Jar"),
    icon: "🌶️",
  },
  {
    id: "bny_19",
    rank: 19,
    slug: "brooklyn-grange",
    name: "Brooklyn Grange",
    aisle: "food-beverage",
    website: "http://www.brooklyngrangefarm.com",
    ecommerceHint: "unknown",
    signals: "world's largest rooftop soil farms; 50,000+ lbs organically-cultivated produce per year; 40+ honeybee hives; hosts weddings and events",
    description: "Brooklyn Grange is the leading rooftop farming and intensive green roofing business in the US, operating the world's largest rooftop soil farms.",
    cohort: 2,
    claimStatus: "unclaimed",
    attribution: attribution("Brooklyn Grange"),
    icon: "🥬",
  },
  {
    id: "bny_20",
    rank: 20,
    slug: "devore-fidelity",
    name: "DeVore Fidelity",
    aisle: "electronics",
    website: "http://www.devorefidelity.com",
    ecommerceHint: "unknown",
    signals: "award-winning speakers renowned worldwide; hand-built in Brooklyn",
    description: "DeVore Fidelity hand builds award-winning state of the art speakers in Brooklyn, renowned the world over for their unsurpassed performance and musicality.",
    cohort: 2,
    claimStatus: "unclaimed",
    attribution: attribution("DeVore Fidelity"),
    icon: "🔊",
  },
  {
    id: "bny_21",
    rank: 21,
    slug: "teknikio",
    name: "Teknikio",
    aisle: "electronics",
    website: "https://www.teknikio.com/",
    ecommerceHint: "store",
    signals: "Award-winning educational electronics sets",
    description: "Award-winning, educational electronics sets for building and activating toys, gadgets, and wearables.",
    cohort: 2,
    claimStatus: "unclaimed",
    attribution: attribution("Teknikio"),
    icon: "🤖",
  },
  {
    id: "bny_22",
    rank: 22,
    slug: "turntable-lab-inc",
    name: "Turntable Lab Inc.",
    aisle: "electronics",
    website: "https://www.turntablelab.com/",
    ecommerceHint: "store",
    signals: "",
    description: "DJ-focused music store stocking vinyl records, CDs, turntables, headphones & accessories.",
    cohort: 2,
    claimStatus: "unclaimed",
    attribution: attribution("Turntable Lab Inc."),
    icon: "🎧",
  },
  {
    id: "bny_23",
    rank: 23,
    slug: "voltaic-systems",
    name: "Voltaic Systems",
    aisle: "electronics",
    website: "https://www.voltaicsystems.com",
    ecommerceHint: "store",
    signals: "",
    description: "Voltaic Systems designs and manufactures remote power systems for IoT sensors and personal electronics, including small solar panels, battery packs and mounting systems.",
    cohort: 2,
    claimStatus: "unclaimed",
    attribution: attribution("Voltaic Systems"),
    icon: "🔋",
  },
  {
    id: "bny_24",
    rank: 24,
    slug: "act-supplies",
    name: "ACT Supplies",
    aisle: "office-services",
    website: "https://www.actsupplies.com/",
    ecommerceHint: "store",
    signals: "over 50,000 available items in online catalog",
    description: "ACT Supplies stocks and ships office technology, desks, toner, paper supplies, and home and office furniture across the U.S.",
    cohort: 2,
    claimStatus: "unclaimed",
    attribution: attribution("ACT Supplies"),
    icon: "🖇️",
  },
  {
    id: "bny_25",
    rank: 25,
    slug: "leeway-home",
    name: "Leeway Home",
    aisle: "local-brands",
    website: "https://leewayhome.co/",
    ecommerceHint: "store",
    signals: "Direct-to-consumer brand with kit-based product line",
    description: "Leeway Home is a direct-to-consumer homewares brand combining ceramics, glassware and flatware into simple, affordable all-in-one table-setting kits.",
    cohort: 2,
    claimStatus: "unclaimed",
    attribution: attribution("Leeway Home"),
    icon: "🍽️",
  },
  {
    id: "bny_26",
    rank: 26,
    slug: "sin",
    name: "SIN",
    aisle: "local-brands",
    website: "https://virginiasin.com/",
    ecommerceHint: "store",
    signals: "",
    description: "SIN is a ceramics home goods brand with a mission to create warmth and happiness in homes across the world by putting the fun into the functional.",
    cohort: 2,
    claimStatus: "unclaimed",
    attribution: attribution("SIN"),
    icon: "🏺",
  },
  {
    id: "bny_27",
    rank: 27,
    slug: "stitchroom",
    name: "Stitchroom",
    aisle: "local-brands",
    website: "https://www.stitchroom.com/",
    ecommerceHint: "store",
    signals: "",
    description: "Stitchroom makes buying custom pillows, cushions, ottomans, poufs, headboards, curtains, banquettes and upholstery as simple as retail.",
    cohort: 2,
    claimStatus: "unclaimed",
    attribution: attribution("Stitchroom"),
    icon: "🛋️",
  },
  {
    id: "bny_28",
    rank: 28,
    slug: "haptic-lab",
    name: "Haptic Lab",
    aisle: "local-brands",
    website: "https://www.hapticlab.com/",
    ecommerceHint: "unknown",
    signals: "Founded by architect Emily Fischer in 2009; certified B Corp since 2019",
    description: "Haptic Lab designs sustainable art pieces that connect people and the planet to benefit positive climate action.",
    cohort: 2,
    claimStatus: "unclaimed",
    attribution: attribution("Haptic Lab"),
    icon: "🪁",
  },
  {
    id: "bny_29",
    rank: 29,
    slug: "f-schumacher-co",
    name: "F. Schumacher & Co.",
    aisle: "local-brands",
    website: "https://fschumacher.com/",
    ecommerceHint: "unknown",
    signals: "Family-owned since 1889; self-described style leader and design innovator in luxury fabrics",
    description: "A family-owned company since 1889, Schumacher is a style leader and design innovator, specializing in luxury fabrics, wallcoverings, trims and pillows.",
    cohort: 2,
    claimStatus: "unclaimed",
    attribution: attribution("F. Schumacher & Co."),
    icon: "🧵",
  },
  {
    id: "bny_30",
    rank: 30,
    slug: "zero-maria-cornejo",
    name: "Zero + Maria Cornejo",
    aisle: "apparel-merch",
    website: "https://zeromariacornejo.com/",
    ecommerceHint: "store",
    signals: "",
    description: "A minimalist luxury fashion boutique showcasing women's fashions in unusual, architectural styles.",
    cohort: 2,
    claimStatus: "unclaimed",
    attribution: attribution("Zero + Maria Cornejo"),
    icon: "🧥",
  },
  {
    id: "bny_31",
    rank: 31,
    slug: "kirrin-finch",
    name: "Kirrin Finch",
    aisle: "apparel-merch",
    website: "https://kirrinfinch.com/",
    ecommerceHint: "unknown",
    signals: "Distinct DTC brand mission breaking down gender boundaries in fashion",
    description: "Kirrin Finch is a conscientious clothing company that creates menswear-inspired apparel designed to fit a range of women and non-binary folks.",
    cohort: 3,
    claimStatus: "unclaimed",
    attribution: attribution("Kirrin Finch"),
    icon: "👔",
  },
  {
    id: "bny_32",
    rank: 32,
    slug: "blackstock-weber",
    name: "Blackstock & Weber",
    aisle: "apparel-merch",
    website: "https://www.blackstockandweber.com/",
    ecommerceHint: "store",
    signals: "",
    description: "Blackstock & Weber is a Brooklyn-based fashion and lifestyle brand founded by Chris Echevarria.",
    cohort: 3,
    claimStatus: "unclaimed",
    attribution: attribution("Blackstock & Weber"),
    icon: "🥿",
  },
  {
    id: "bny_33",
    rank: 33,
    slug: "tracey-tanner",
    name: "Tracey Tanner",
    aisle: "apparel-merch",
    website: "https://traceytanner.com/",
    ecommerceHint: "store",
    signals: "Handmade from the finest Italian leather in the USA",
    description: "Handmade leather accessories made from the finest Italian leather in the USA, Brooklyn based.",
    cohort: 3,
    claimStatus: "unclaimed",
    attribution: attribution("Tracey Tanner"),
    icon: "👝",
  },
  {
    id: "bny_34",
    rank: 34,
    slug: "sartorous",
    name: "Sartorous",
    aisle: "apparel-merch",
    website: "http://www.sartorous.com",
    ecommerceHint: "store",
    signals: "More than 12 years producing a full range of accessories",
    description: "Sartorous is a specialty clothing accessory company producing and distributing a full range of top-quality suspenders, braces, men's garters, and other related products.",
    cohort: 3,
    claimStatus: "unclaimed",
    attribution: attribution("Sartorous"),
    icon: "🤵",
  },
  {
    id: "bny_35",
    rank: 35,
    slug: "piccolini-ny",
    name: "Piccolini NY",
    aisle: "apparel-merch",
    website: "https://piccolinyshop.com/",
    ecommerceHint: "store",
    signals: "",
    description: "One-stop hip kid-o shop!",
    cohort: 3,
    claimStatus: "unclaimed",
    attribution: attribution("Piccolini NY"),
    icon: "🧸",
  },
  {
    id: "bny_36",
    rank: 36,
    slug: "jasco-designs",
    name: "Jasco Designs",
    aisle: "apparel-merch",
    website: "https://www.lilynily.com/",
    ecommerceHint: "store",
    signals: "Retail brand (Lily Nily) with dedicated product site",
    description: "Retail luxury goods and jewelry.",
    cohort: 3,
    claimStatus: "unclaimed",
    attribution: attribution("Jasco Designs"),
    icon: "📿",
  },
  {
    id: "bny_37",
    rank: 37,
    slug: "luxholdups",
    name: "Luxholdups",
    aisle: "local-brands",
    website: "https://www.etsy.com/shop/luxholdups/",
    ecommerceHint: "store",
    signals: "Active Etsy shop as primary storefront",
    description: "Luxholdups is a Brooklyn-based design and fabrication studio specializing in custom lucite and metal furnishings, including architectural hardware, shelving, and furniture.",
    cohort: 3,
    claimStatus: "unclaimed",
    attribution: attribution("Luxholdups"),
    icon: "🪞",
  },
  {
    id: "bny_38",
    rank: 38,
    slug: "scott-jordan-furniture",
    name: "Scott Jordan Furniture",
    aisle: "local-brands",
    website: "http://www.scottjordan.com/",
    ecommerceHint: "store",
    signals: "",
    description: "Scott Jordan Furniture is a furniture manufacturer.",
    cohort: 3,
    claimStatus: "unclaimed",
    attribution: attribution("Scott Jordan Furniture"),
    icon: "🪑",
  },
  {
    id: "bny_39",
    rank: 39,
    slug: "pagani-studio",
    name: "Pagani Studio",
    aisle: "local-brands",
    website: "http://www.paganistudio.com",
    ecommerceHint: "unknown",
    signals: "Over two decades collaborating with prestigious interior designers worldwide, including a large-scale chandelier for President and Mrs. Obama in the White House",
    description: "PaganiStudio is a traditional design atelier specializing in contemporary, handmade lighting fixtures.",
    cohort: 3,
    claimStatus: "unclaimed",
    attribution: attribution("Pagani Studio"),
    icon: "💡",
  },
  {
    id: "bny_40",
    rank: 40,
    slug: "lights-up",
    name: "Lights Up",
    aisle: "local-brands",
    website: "http://www.lightsuplighting.com",
    ecommerceHint: "unknown",
    signals: "Manufacturing in Brooklyn since 1987; family-run and woman-owned; handmade wire frames and shades",
    description: "Lights Up has been designing and manufacturing sophisticated, durable and affordable lighting in Brooklyn since 1987 as a family-run, woman-owned business.",
    cohort: 3,
    claimStatus: "unclaimed",
    attribution: attribution("Lights Up"),
    icon: "🏮",
  },
  {
    id: "bny_41",
    rank: 41,
    slug: "ojas",
    name: "Ojas",
    aisle: "electronics",
    website: "https://ojas.nyc/",
    ecommerceHint: "unknown",
    signals: "Cult-followed hi-fi speaker maker with own product line",
    description: "With a particular interest in high efficiency speakers and low powered tube amplifiers, Ojas audio equipment aims to bring realistic, natural sound to the listener.",
    cohort: 3,
    claimStatus: "unclaimed",
    attribution: attribution("Ojas"),
    icon: "🎚️",
  },
  {
    id: "bny_42",
    rank: 42,
    slug: "fotofoto",
    name: "FotoFoto",
    aisle: "electronics",
    website: "https://fotofoto.io/",
    ecommerceHint: "unknown",
    signals: "Circular/sustainability angle on a consumer camera product",
    description: "FOTOFOTO refurbishes and recycles disposable cameras to give them a second life, responsibly disposing of parts when necessary.",
    cohort: 3,
    claimStatus: "unclaimed",
    attribution: attribution("FotoFoto"),
    icon: "📷",
  },
  {
    id: "bny_43",
    rank: 43,
    slug: "ares-printing",
    name: "Ares Printing",
    aisle: "packaging",
    website: "http://www.aresny.com",
    ecommerceHint: "unknown",
    signals: "two of New York state's largest sheet-fed printing presses; Yard tenant since 1981; serves cosmetics, pharma, electronics, and food & beverage industries; 100% co-generated power",
    description: "Established in 1979, ARES Printing and Packaging designs and manufactures paperboard, folding cartons, and point-of-purchase displays with a strong focus on sustainability.",
    cohort: 3,
    claimStatus: "unclaimed",
    attribution: attribution("Ares Printing"),
    icon: "🖨️",
  },
  {
    id: "bny_44",
    rank: 44,
    slug: "packaging-plus-llc",
    name: "Packaging Plus LLC.",
    aisle: "packaging",
    website: "https://packagingplususa.com/",
    ecommerceHint: "unknown",
    signals: "",
    description: "Packaging Plus, LLC. offers a wide range of catering to go bags and custom printed shopping bags for all your packaging needs.",
    cohort: 3,
    claimStatus: "unclaimed",
    attribution: attribution("Packaging Plus LLC."),
    icon: "🛍️",
  },
  {
    id: "bny_45",
    rank: 45,
    slug: "duggal-visual-solutions",
    name: "Duggal Visual Solutions",
    aisle: "office-services",
    website: "https://duggal.com/",
    ecommerceHint: "unknown",
    signals: "industry leader; occupies multiple buildings (25, 500, 303, 268, 314); produces world-class events and stadium-size installations",
    description: "Duggal Visual Solutions specializes in producing compelling visual experiences and transforming environments, from global rollouts to stadium-size installations and headline exhibitions.",
    cohort: 3,
    claimStatus: "unclaimed",
    attribution: attribution("Duggal Visual Solutions"),
    icon: "🖼️",
  },
  {
    id: "bny_46",
    rank: 46,
    slug: "brinks",
    name: "Brinks",
    aisle: "logistics",
    website: "https://us.brinks.com/",
    ecommerceHint: "unknown",
    signals: "global armored transport and cash logistics provider",
    description: "Brinks provides armored car service, money processing, long-distance transport of valuables, vaulting, and other value-added solutions.",
    cohort: 3,
    claimStatus: "unclaimed",
    attribution: attribution("Brinks"),
    icon: "🚛",
  },
  {
    id: "bny_47",
    rank: 47,
    slug: "haddads-inc",
    name: "Haddad's Inc.",
    aisle: "logistics",
    website: "https://haddadsinc.com/",
    ecommerceHint: "unknown",
    signals: "3,400+ television and film productions; self-described leader in production rental equipment",
    description: "Haddad's rents production equipment worldwide and is the leader in production rental equipment, with fleet hubs in New York, New Jersey, Michigan, and Massachusetts.",
    cohort: 3,
    claimStatus: "unclaimed",
    attribution: attribution("Haddad's Inc."),
    icon: "🎬",
  },
  {
    id: "bny_48",
    rank: 48,
    slug: "atz-trading-inc",
    name: "ATZ Trading Inc.",
    aisle: "logistics",
    website: "https://www.atztrade.com",
    ecommerceHint: "unknown",
    signals: "next-day delivery service for Tri-state area",
    description: "ATZTRADE.COM is a direct importer/exporter of fresh and frozen seafoods, dried foods, fresh produce, and customized packaging materials for restaurants and supermarkets.",
    cohort: 3,
    claimStatus: "unclaimed",
    attribution: attribution("ATZ Trading Inc."),
    icon: "🐟",
  },
  {
    id: "bny_49",
    rank: 49,
    slug: "barronarts",
    name: "Barronarts",
    aisle: "fabrication",
    website: "https://www.barronarts.com/",
    ecommerceHint: "unknown",
    signals: "claims finest stretcher frames in the world; ships worldwide; serves discerning artists, galleries, and museums",
    description: "Barronarts designs and constructs stretcher frames, artist panels, and floater frames, with full canvas stretching, custom priming, and worldwide shipping.",
    cohort: 3,
    claimStatus: "unclaimed",
    attribution: attribution("Barronarts"),
    icon: "🎨",
  },
  {
    id: "bny_50",
    rank: 50,
    slug: "evan-hughes-studio",
    name: "Evan Hughes Studio",
    aisle: "fabrication",
    website: "http://www.evanhughesstudio.com",
    ecommerceHint: "unknown",
    signals: "designing and building furniture since 1978",
    description: "Evan Hughes is a designer and builder of custom and limited edition furniture since 1978.",
    cohort: 3,
    claimStatus: "unclaimed",
    attribution: attribution("Evan Hughes Studio"),
    icon: "🪵",
  },
];

export function bnyBySlug(slug?: string): BnyStorefront | undefined {
  return BNY_ROSTER.find((s) => s.slug === slug);
}

export function bnyByAisle(aisleSlug: string): BnyStorefront[] {
  return BNY_ROSTER.filter((s) => s.aisle === aisleSlug);
}

export function bnyByCohort(cohort: 1 | 2 | 3): BnyStorefront[] {
  return BNY_ROSTER.filter((s) => s.cohort === cohort);
}
