/**
 * Synced Shopify catalog snapshots — GENERATED FILE, do not edit by hand.
 *
 * Regenerated by scripts/sync-shopify-snapshot.mjs (last sync: 2026-06-12).
 * Serves as the catalog source for integrated storefronts when no
 * SHOPIFY_STOREFRONT_API_TOKEN is configured at runtime; the live Storefront
 * API takes precedence when it is.
 */

export interface SnapshotProduct {
  id: string;
  name: string;
  price: number;
  unit: string;
  imageUrl?: string;
  url?: string;
}

export const SHOPIFY_SNAPSHOTS: Record<string, SnapshotProduct[]> = {
  "grahmos-marketbny.myshopify.com": [
    {
      id: "gid://shopify/Product/15022586396783",
      name: "Gift Card",
      price: 10,
      unit: "each",
      imageUrl: "https://cdn.shopify.com/s/files/1/0729/2311/9727/files/gift_card.png?v=1779837344",
      url: "https://grahmos-marketbny.myshopify.com/products/gift-card",
    },
    {
      id: "gid://shopify/Product/15044321706095",
      name: "The Yard Tote",
      price: 48,
      unit: "each",
      url: "https://grahmos-marketbny.myshopify.com/products/the-yard-tote",
    },
    {
      id: "gid://shopify/Product/15044321738863",
      name: "Navy Yard Crewneck",
      price: 72,
      unit: "each",
      url: "https://grahmos-marketbny.myshopify.com/products/navy-yard-crewneck",
    },
    {
      id: "gid://shopify/Product/15044321804399",
      name: "The Maker's Gift Box",
      price: 95,
      unit: "each",
      url: "https://grahmos-marketbny.myshopify.com/products/the-makers-gift-box",
    },
    {
      id: "gid://shopify/Product/15044321837167",
      name: "Yard Roast — Whole Bean, 12 oz",
      price: 22,
      unit: "each",
      url: "https://grahmos-marketbny.myshopify.com/products/yard-roast-whole-bean-12-oz",
    },
    {
      id: "gid://shopify/Product/15044321869935",
      name: "Packaging Sample Library",
      price: 35,
      unit: "each",
      url: "https://grahmos-marketbny.myshopify.com/products/packaging-sample-library",
    },
    {
      id: "gid://shopify/Product/15044321902703",
      name: "Fabrication Materials Sampler",
      price: 45,
      unit: "each",
      url: "https://grahmos-marketbny.myshopify.com/products/fabrication-materials-sampler",
    },
    {
      id: "gid://shopify/Product/15044321935471",
      name: "Prototype Sourcing Consult — First Quote Free",
      price: 0,
      unit: "each",
      url: "https://grahmos-marketbny.myshopify.com/products/prototype-sourcing-consult-first-quote-free",
    },
    {
      id: "gid://shopify/Product/15044321968239",
      name: "Small-Batch Production Starter — Deposit",
      price: 250,
      unit: "each",
      url: "https://grahmos-marketbny.myshopify.com/products/small-batch-production-starter-deposit",
    },
    {
      id: "gid://shopify/Product/15044322001007",
      name: "Electronics Bring-Up Bench Kit",
      price: 65,
      unit: "each",
      url: "https://grahmos-marketbny.myshopify.com/products/electronics-bring-up-bench-kit",
    },
    {
      id: "gid://shopify/Product/15044322033775",
      name: "The Navigator's Field Notebook",
      price: 18,
      unit: "each",
      url: "https://grahmos-marketbny.myshopify.com/products/the-navigators-field-notebook",
    },
    {
      id: "gid://shopify/Product/15044322099311",
      name: "Yard Crate — Local Pantry Edition",
      price: 68,
      unit: "each",
      url: "https://grahmos-marketbny.myshopify.com/products/yard-crate-local-pantry-edition",
    },
  ],
};
