/**
 * Synced Shopify catalog snapshots — GENERATED FILE, do not edit by hand.
 *
 * Regenerated by scripts/sync-shopify-snapshot.mjs (last sync: 2026-07-21).
 * Serves as the catalog source for integrated storefronts when no
 * SHOPIFY_STOREFRONT_API_TOKEN is configured at runtime; the live Storefront
 * API takes precedence when it is.
 */

export interface SnapshotProduct {
  id: string;
  name: string;
  price: number;
  unit: string;
  imageUrl?: string;
  url?: string;
}

export const SHOPIFY_SNAPSHOTS: Record<string, SnapshotProduct[]> = {
  "grahmos-marketbny.myshopify.com": [
    {
      id: "gid://shopify/Product/15022586396783",
      name: "Gift Card",
      price: 10,
      unit: "each",
      imageUrl: "https://cdn.shopify.com/s/files/1/0729/2311/9727/files/gift_card.png?v=1779837344",
      url: "https://grahmos-marketbny.myshopify.com/products/gift-card",
    },
    {
      id: "gid://shopify/Product/15044321706095",
      name: "The Yard Tote",
      price: 48,
      unit: "each",
      url: "https://grahmos-marketbny.myshopify.com/products/the-yard-tote",
    },
    {
      id: "gid://shopify/Product/15044321738863",
      name: "Navy Yard Crewneck",
      price: 72,
      unit: "each",
      url: "https://grahmos-marketbny.myshopify.com/products/navy-yard-crewneck",
    },
    {
      id: "gid://shopify/Product/15044321804399",
      name: "The Maker's Gift Box",
      price: 95,
      unit: "each",
      url: "https://grahmos-marketbny.myshopify.com/products/the-makers-gift-box",
    },
    {
      id: "gid://shopify/Product/15044321837167",
      name: "Yard Roast — Whole Bean, 12 oz",
      price: 22,
      unit: "each",
      url: "https://grahmos-marketbny.myshopify.com/products/yard-roast-whole-bean-12-oz",
    },
    {
      id: "gid://shopify/Product/15044321869935",
      name: "Packaging Sample Library",
      price: 35,
      unit: "each",
      url: "https://grahmos-marketbny.myshopify.com/products/packaging-sample-library",
    },
    {
      id: "gid://shopify/Product/15044321902703",
      name: "Fabrication Materials Sampler",
      price: 45,
      unit: "each",
      url: "https://grahmos-marketbny.myshopify.com/products/fabrication-materials-sampler",
    },
    {
      id: "gid://shopify/Product/15044321935471",
      name: "Prototype Sourcing Consult — First Quote Free",
      price: 0,
      unit: "each",
      url: "https://grahmos-marketbny.myshopify.com/products/prototype-sourcing-consult-first-quote-free",
    },
    {
      id: "gid://shopify/Product/15044321968239",
      name: "Small-Batch Production Starter — Deposit",
      price: 250,
      unit: "each",
      url: "https://grahmos-marketbny.myshopify.com/products/small-batch-production-starter-deposit",
    },
    {
      id: "gid://shopify/Product/15044322001007",
      name: "Electronics Bring-Up Bench Kit",
      price: 65,
      unit: "each",
      url: "https://grahmos-marketbny.myshopify.com/products/electronics-bring-up-bench-kit",
    },
    {
      id: "gid://shopify/Product/15044322033775",
      name: "The Navigator's Field Notebook",
      price: 18,
      unit: "each",
      url: "https://grahmos-marketbny.myshopify.com/products/the-navigators-field-notebook",
    },
    {
      id: "gid://shopify/Product/15044322099311",
      name: "Yard Crate — Local Pantry Edition",
      price: 68,
      unit: "each",
      url: "https://grahmos-marketbny.myshopify.com/products/yard-crate-local-pantry-edition",
    },
  ],
  // GrahmOS Trending — a GrahmOS-built (mall-owned) store, NOT a tenant brand.
  "grahmos-accio.myshopify.com": [
    {
      id: "gid://shopify/Product/9426086691055",
      name: "Portable Hydraulic Car Lift — 5,000 lb Capacity",
      price: 1499,
      unit: "each",
      imageUrl: "https://cdn.shopify.com/s/files/1/0809/9040/4847/files/pexels-photo-8986119.jpg?v=1781327039",
      url: "https://grahmos-accio.myshopify.com/products/portable-hydraulic-car-lift-5-000-lb-capacity",
    },
    {
      id: "gid://shopify/Product/9426086625519",
      name: "Multi-Wavelength Red Light Therapy Panel",
      price: 899,
      unit: "each",
      imageUrl: "https://cdn.shopify.com/s/files/1/0809/9040/4847/files/pexels-photo-7216285.jpg?v=1781327031",
      url: "https://grahmos-accio.myshopify.com/products/multi-wavelength-red-light-therapy-panel",
    },
    {
      id: "gid://shopify/Product/9426086723823",
      name: "Smart Electric Standing Desk — Dual-Motor, App + Bluetooth",
      price: 399,
      unit: "each",
      imageUrl: "https://cdn.shopify.com/s/files/1/0809/9040/4847/files/pexels-photo-10321957.jpg?v=1781327044",
      url: "https://grahmos-accio.myshopify.com/products/smart-electric-standing-desk-dual-motor-app-bluetooth",
    },
    {
      id: "gid://shopify/Product/9426086658287",
      name: "Smart Health Ring — Sleep, HRV & Recovery (No Subscription)",
      price: 299,
      unit: "each",
      imageUrl: "https://cdn.shopify.com/s/files/1/0809/9040/4847/files/pexels-photo-34241802.jpg?v=1781327035",
      url: "https://grahmos-accio.myshopify.com/products/smart-health-ring-sleep-hrv-amp-recovery-no-subscription",
    },
    {
      id: "gid://shopify/Product/9426086756591",
      name: "EVA Perforated Beach & Everyday Tote",
      price: 45,
      unit: "each",
      imageUrl: "https://cdn.shopify.com/s/files/1/0809/9040/4847/files/pexels-photo-29736141.jpg?v=1781327047",
      url: "https://grahmos-accio.myshopify.com/products/eva-perforated-beach-amp-everyday-tote",
    },
    {
      id: "gid://shopify/Product/9426086920431",
      name: "Ceremonial-Grade Japanese Matcha — 30g Tin",
      price: 35,
      unit: "each",
      imageUrl: "https://cdn.shopify.com/s/files/1/0809/9040/4847/files/pexels-photo-8330272.jpg?v=1781327068",
      url: "https://grahmos-accio.myshopify.com/products/ceremonial-grade-japanese-matcha-30g-tin",
    },
    {
      id: "gid://shopify/Product/9426086887663",
      name: "Prebiotic Functional Soda — Variety 12-Pack",
      price: 32,
      unit: "each",
      imageUrl: "https://cdn.shopify.com/s/files/1/0809/9040/4847/files/pexels-photo-5860659.jpg?v=1781327062",
      url: "https://grahmos-accio.myshopify.com/products/prebiotic-functional-soda-variety-12-pack",
    },
    {
      id: "gid://shopify/Product/9426086789359",
      name: "40oz Stainless Vacuum-Insulated Tumbler with Straw",
      price: 24,
      unit: "each",
      imageUrl: "https://cdn.shopify.com/s/files/1/0809/9040/4847/files/pexels-photo-8341885.jpg?v=1781327052",
      url: "https://grahmos-accio.myshopify.com/products/40oz-stainless-vacuum-insulated-tumbler-with-straw",
    },
    {
      id: "gid://shopify/Product/9426086854895",
      name: "Electrolyte Hydration Powder — 30 Sticks",
      price: 30,
      unit: "each",
      imageUrl: "https://cdn.shopify.com/s/files/1/0809/9040/4847/files/pexels-photo-33107433.jpg?v=1781327056",
      url: "https://grahmos-accio.myshopify.com/products/electrolyte-hydration-powder-30-sticks",
    },
  ],
  // Mamba Health — an INDEPENDENT tenant brand leasing a mall unit (sf_11).
  "mamba-health-intelligence-7m3de.myshopify.com": [
    {
      id: "gid://shopify/Product/9179304558808",
      name: "Mamba Performance Towel",
      price: 29.99,
      unit: "each",
      imageUrl: "https://cdn.shopify.com/s/files/1/0811/8009/8776/files/performance-towel.jpg?v=1775344055",
      url: "https://mamba-health-intelligence-7m3de.myshopify.com/products/mamba-performance-towel",
    },
    {
      id: "gid://shopify/Product/9179304624344",
      name: "Mamba Sleep Stack",
      price: 59.99,
      unit: "each",
      imageUrl: "https://cdn.shopify.com/s/files/1/0811/8009/8776/files/sleep-stack.jpg?v=1775344130",
      url: "https://mamba-health-intelligence-7m3de.myshopify.com/products/mamba-sleep-stack",
    },
    {
      id: "gid://shopify/Product/9179304722648",
      name: "Mamba Recovery Kit",
      price: 149.99,
      unit: "each",
      imageUrl: "https://cdn.shopify.com/s/files/1/0811/8009/8776/files/recovery-kit.jpg?v=1775344219",
      url: "https://mamba-health-intelligence-7m3de.myshopify.com/products/mamba-recovery-kit",
    },
    {
      id: "gid://shopify/Product/9181376872664",
      name: "Luxury Bamboo Bathrobe",
      price: 185,
      unit: "each",
      imageUrl: "https://cdn.shopify.com/s/files/1/0811/8009/8776/files/bamboo-bathrobe.jpg?v=1775344261",
      url: "https://mamba-health-intelligence-7m3de.myshopify.com/products/luxury-bamboo-bathrobe",
    },
    {
      id: "gid://shopify/Product/9181376905432",
      name: "Red Light Therapy Belt",
      price: 295,
      unit: "each",
      imageUrl: "https://cdn.shopify.com/s/files/1/0811/8009/8776/files/red-light-belt.jpg?v=1775344319",
      url: "https://mamba-health-intelligence-7m3de.myshopify.com/products/red-light-therapy-belt",
    },
    {
      id: "gid://shopify/Product/9181376970968",
      name: "Mamba Hydrogen Water Bottle",
      price: 125,
      unit: "each",
      imageUrl: "https://cdn.shopify.com/s/files/1/0811/8009/8776/files/hydrogen-bottle.jpg?v=1775344396",
      url: "https://mamba-health-intelligence-7m3de.myshopify.com/products/mamba-hydrogen-water-bottle",
    },
    {
      id: "gid://shopify/Product/9181377167576",
      name: "Bespoke Walnut Supplement Organizer",
      price: 65,
      unit: "each",
      imageUrl: "https://cdn.shopify.com/s/files/1/0811/8009/8776/files/walnut-organizer.jpg?v=1775344469",
      url: "https://mamba-health-intelligence-7m3de.myshopify.com/products/bespoke-walnut-supplement-organizer",
    },
    {
      id: "gid://shopify/Product/9181377396952",
      name: "Ceramic Ritual Matcha Set (Black)",
      price: 95,
      unit: "each",
      imageUrl: "https://cdn.shopify.com/s/files/1/0811/8009/8776/files/matcha-set.jpg?v=1775344552",
      url: "https://mamba-health-intelligence-7m3de.myshopify.com/products/ceramic-ritual-matcha-set-black",
    },
    {
      id: "gid://shopify/Product/9181377462488",
      name: "Silk Sleep Mask (Silver Ion)",
      price: 35,
      unit: "each",
      imageUrl: "https://cdn.shopify.com/s/files/1/0811/8009/8776/files/silk-sleep-mask.jpg?v=1775344601",
      url: "https://mamba-health-intelligence-7m3de.myshopify.com/products/silk-sleep-mask-silver-ion",
    },
    {
      id: "gid://shopify/Product/9181377855704",
      name: "Weighted Bamboo Blanket",
      price: 195,
      unit: "each",
      imageUrl: "https://cdn.shopify.com/s/files/1/0811/8009/8776/files/weighted-blanket.jpg?v=1775344646",
      url: "https://mamba-health-intelligence-7m3de.myshopify.com/products/weighted-bamboo-blanket",
    },
    {
      id: "gid://shopify/Product/9181377954008",
      name: "Vacuum Pantry Set (10pc)",
      price: 350,
      unit: "each",
      imageUrl: "https://cdn.shopify.com/s/files/1/0811/8009/8776/files/vacuum-pantry.jpg?v=1775344694",
      url: "https://mamba-health-intelligence-7m3de.myshopify.com/products/vacuum-pantry-set-10pc",
    },
    {
      id: "gid://shopify/Product/9181377986776",
      name: "Starter Membership — The Daily Ritual",
      price: 250,
      unit: "each",
      imageUrl: "https://cdn.shopify.com/s/files/1/0811/8009/8776/files/membership-starter.jpg?v=1775344762",
      url: "https://mamba-health-intelligence-7m3de.myshopify.com/products/starter-membership-the-daily-ritual",
    },
    {
      id: "gid://shopify/Product/9181378183384",
      name: "Pro Membership — The Performance Lab",
      price: 1250,
      unit: "each",
      imageUrl: "https://cdn.shopify.com/s/files/1/0811/8009/8776/files/membership-pro.jpg?v=1775344797",
      url: "https://mamba-health-intelligence-7m3de.myshopify.com/products/pro-membership-the-performance-lab",
    },
    {
      id: "gid://shopify/Product/9181379854552",
      name: "Executive Membership — The Elite Sanctuary",
      price: 5000,
      unit: "each",
      imageUrl: "https://cdn.shopify.com/s/files/1/0811/8009/8776/files/membership-executive.jpg?v=1775344824",
      url: "https://mamba-health-intelligence-7m3de.myshopify.com/products/executive-membership-the-elite-sanctuary",
    },
    {
      id: "gid://shopify/Product/9181379952856",
      name: "Enterprise Membership — Clinic-in-a-Box",
      price: 25000,
      unit: "each",
      imageUrl: "https://cdn.shopify.com/s/files/1/0811/8009/8776/files/membership-enterprise.jpg?v=1775344854",
      url: "https://mamba-health-intelligence-7m3de.myshopify.com/products/enterprise-membership-clinic-in-a-box",
    },
  ],
};
